source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/china_ios/cocoapods-specs.git'

platform :ios, '12.0'

use_frameworks!
#use_modular_headers!

target 'ZKBaseSwiftProject_Example' do
  
  pod 'ZKBaseSwiftProject', :path => '../'

#  pod 'HandyJSON', :git => 'https://github.com/Miles-Matheson/HandyJSON.git'
#  pod 'GGXSwiftExtension', :path => '~/Documents/GitHub/ggxswiftexten'
  
#  target 'ZKBaseSwiftProject_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
