use_frameworks!

platform :ios, '10.0'

target 'ZKBaseSwiftProject_Example' do
  pod 'ZKBaseSwiftProject', :path => '../'

  target 'ZKBaseSwiftProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
