platform :ios, '10.0'

target 'ZKBaseSwiftProject_Example' do
  use_frameworks!
  
  pod 'ZKBaseSwiftProject', :path => '../'

  pod 'GGXSwiftExtension', :path => '/Users/gaoguangxiao/Documents/GitHub/ggxswiftexten'
  
  target 'ZKBaseSwiftProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
